name: .NET Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: System.Windows.Forms.Ribbon.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    # 安装 NuGet
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1
      
    # 导航到工作区
    - name: Setup NuGet.exe
      run: cd ${{ github.workspace }}/src
      
    # Restore
    - name: Restore nuget
      run: nuget restore $env:Solution_Name
      
    # build the application 
    - name: Build the application
      run: msbuild $env:Solution_Name /p:Platform="Any CPU" /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
